# Generated by Django 5.1.6 on 2025-02-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0003_staff_rename_patients_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Totalbeds', models.IntegerField()),
                ('Availablebeds', models.IntegerField()),
            ],
        ),
    ]
